#!/bin/bash

# temp dir for packaging
TMP=/tmp/turtl-package-chrome
CRX=turtl.zip

nogen=$1

if [ "$nogen" != "--skip-tpl" ]; then
	# generate templates
	echo -n "Regenerating templates so we have the freshest versions..."
	./scripts/generate-templates
	echo "done."
fi

rm -rf $TMP/*

echo -n "Copying extension files to temp directory..."
cp -R -L . $TMP/ 2>&1 | grep -v '.git'
echo "done."

EXTDIR=`realpath .`
mkdir -p $TMP
pushd $TMP/> /dev/null

echo "Packaging extension."

echo "Copying live config over local"
mv config.live.js config.js

echo -n "Zipping..."
zip -r turtl.crx \
	. \
	-x *.git* \
	> /dev/null
echo "done."

mv turtl.crx $EXTDIR/$CRX || {
	echo "Problem moving $TMP/turtl.crx to $EXTDIR/$CRX. Exiting."
	exit 1
}
popd > /dev/null

echo "Clearing tmp dir ($TMP/)"
#rm -rf $TMP

echo "Complete. Created fully-packaged extension: $CRX"
